/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List prior Runs (summary view)
         * @description Returns the metadata for all Runs in the v1 shared scope (FR-024,
         *     FR-025). Sorted by `createdUtc` descending.
         */
        get: operations["listRuns"];
        put?: never;
        /**
         * Generate a new Run (synthetic data + detection results)
         * @description Atomically generates a synthetic dataset using the supplied
         *     `SimulationConfiguration`, runs the deterministic detection pipeline
         *     across every record, and persists the resulting Run to Azure Storage.
         *     Returns the full Run aggregate. (FR-001 … FR-009, FR-022)
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Fetch a full Run aggregate */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                /** @description The `recordId` of the underlying ExpenseRecord. */
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        /** Fetch a single Case (Expense + Detection + optional AI result) */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cases/{caseId}/investigate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                /** @description The `recordId` of the underlying ExpenseRecord. */
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoke the AI investigator on a Case
         * @description Synchronously calls the Microsoft Foundry-backed agent (FR-010 … FR-013)
         *     with structured context for the case. On success, persists the verdict
         *     to the originating Run blob via ETag-conditioned write. On AI failure
         *     or 30 s timeout, returns a result with `status = "Unavailable"` and
         *     does not persist (FR-014).
         */
        post: operations["investigateCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        SimulationConfiguration: {
            /** @description FR-004 — capped at 50 000. */
            recordCount: number;
            /** @default 100 */
            employeeCount: number;
            /**
             * Format: double
             * @description Overall fraud-injection intensity (FR-003).
             */
            intensity: number;
            patternWeights: components["schemas"]["PatternWeights"];
            thresholds?: components["schemas"]["BandThresholds"];
            /** @description Optional seed for reproducible generation. */
            seed?: number | null;
        };
        /**
         * @description Per-pattern weights (FR-002, FR-003). The server normalizes the values
         *     to sum to 1.0; rejects with HTTP 400 if all three are zero or any is
         *     negative.
         */
        PatternWeights: {
            /** Format: double */
            thresholdGaming: number;
            /** Format: double */
            unusualFrequency: number;
            /** Format: double */
            vendorAnomaly: number;
        };
        /** @description FR-008 / FR-009. */
        BandThresholds: {
            /** Format: double */
            low: number;
            /** Format: double */
            high: number;
        };
        BandCounts: {
            high: number;
            medium: number;
            low: number;
        };
        /** @enum {string} */
        ConfidenceBand: "High" | "Medium" | "Low";
        /** @enum {string} */
        FraudPattern: "ThresholdGaming" | "UnusualFrequency" | "VendorAnomaly";
        Employee: {
            /** Format: uuid */
            employeeId: string;
            name: string;
            department: string;
            role: string;
            /** Format: double */
            baselineMonthlyExpense: number;
            typicalCategories?: string[];
            typicalVendors?: string[];
        };
        /**
         * @description Note: `isInjectedFraud` and `injectedPattern` are present **only** in
         *     the full Run blob; they are stripped from any payload sent to the AI
         *     investigator (data-model invariant 1).
         */
        ExpenseRecord: {
            /** Format: uuid */
            recordId: string;
            /** Format: uuid */
            employeeId: string;
            /** Format: date-time */
            submittedUtc: string;
            /** Format: double */
            amount: number;
            category: string;
            vendor: string;
            isInjectedFraud?: boolean;
            injectedPattern?: components["schemas"]["FraudPattern"] | null;
        };
        FeatureContribution: {
            name: string;
            /** Format: double */
            value: number;
            /** Format: double */
            zScore: number;
        };
        DetectionResult: {
            /** Format: uuid */
            recordId: string;
            /** Format: double */
            rawScore: number;
            /** Format: double */
            confidence: number;
            band: components["schemas"]["ConfidenceBand"];
            contributingFeatures: components["schemas"]["FeatureContribution"][];
        };
        /** @enum {string} */
        InvestigationStatus: "Succeeded" | "Unavailable";
        /** @enum {string} */
        FraudLikelihood: "Likely" | "Unlikely" | "Inconclusive";
        /**
         * @description FR-012 — when `status = "Succeeded"`, all of `verdict`, `rationale`,
         *     `keySignals`, `recommendedAction` MUST be present (SC-008). When
         *     `status = "Unavailable"`, `unavailableReason` MUST be present and
         *     the four success fields MUST be omitted (FR-014).
         */
        AiInvestigationResult: {
            /** Format: uuid */
            recordId: string;
            /** Format: uuid */
            runId: string;
            /** Format: date-time */
            requestedUtc: string;
            /** Format: date-time */
            completedUtc?: string | null;
            status: components["schemas"]["InvestigationStatus"];
            verdict?: components["schemas"]["FraudLikelihood"] | null;
            rationale?: string | null;
            keySignals?: string[] | null;
            recommendedAction?: string | null;
            unavailableReason?: string | null;
        };
        Case: {
            expense: components["schemas"]["ExpenseRecord"];
            employee: components["schemas"]["Employee"];
            detection: components["schemas"]["DetectionResult"];
            investigation?: components["schemas"]["AiInvestigationResult"] | null;
        };
        Run: {
            /** Format: uuid */
            runId: string;
            /** @description FR-025 placeholder; constant `"v1"` until per-user scoping ships. */
            ownerId: string;
            /** Format: date-time */
            createdUtc: string;
            configuration: components["schemas"]["SimulationConfiguration"];
            employees: components["schemas"]["Employee"][];
            expenses: components["schemas"]["ExpenseRecord"][];
            detectionResults: components["schemas"]["DetectionResult"][];
            /** @description Map keyed by `recordId` (the Case's underlying ExpenseRecord). */
            investigations: {
                [key: string]: components["schemas"]["AiInvestigationResult"];
            };
            bandCounts: components["schemas"]["BandCounts"];
        };
        RunSummary: {
            /** Format: uuid */
            runId: string;
            /** Format: date-time */
            createdUtc: string;
            recordCount: number;
            bandCounts: components["schemas"]["BandCounts"];
            /** Format: double */
            intensity: number;
            patternWeights: components["schemas"]["PatternWeights"];
            investigationCount: number;
        };
        RunSummaryPage: {
            items: components["schemas"]["RunSummary"][];
            continuationToken?: string | null;
        };
    };
    responses: {
        /** @description Validation error (FR-021) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Run or Case not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unhandled server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        RunId: string;
        /** @description The `recordId` of the underlying ExpenseRecord. */
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRuns: {
        parameters: {
            query?: {
                take?: number;
                continuationToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryPage"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationConfiguration"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                /** @description The `recordId` of the underlying ExpenseRecord. */
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    investigateCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
                /** @description The `recordId` of the underlying ExpenseRecord. */
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investigation completed (success or graceful unavailable) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiInvestigationResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
